import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'es' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  es: {
    // Navigation
    'nav.inicio': 'Inicio',
    'nav.favoritos': 'Favoritos',
    'nav.hogar': 'Hogar',
    'nav.perfil': 'Perfil',
    
    // Profile Menu
    'profile.view_profile': 'Ver Perfil',
    'profile.login': 'Inicia sesión / Regístrate',
    'profile.register_property': 'Registra propiedad',
    'profile.dashboard': 'Panel de control',
    'profile.settings': 'Configuración',
    'profile.language': 'Idioma',

    'profile.logout': 'Cerrar sesión',
    'header.language': 'Idioma',
    'header.english': 'English',
    'header.spanish': 'Español',
    'header.logout': 'Cerrar sesión',
    'header.profile': 'Perfil',
    
    // Languages
    'language.spanish': 'Español',
    'language.english': 'English',
    
    // Auth
    'auth.signin': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.role': 'Soy un',
    'auth.tenant': 'Inquilino',
    'auth.hoster': 'Anfitrión',
    'auth.demo_tenant': 'Demo Inquilino',
    'auth.demo_hoster': 'Demo Anfitrión',
    
    // Search
    'search.placeholder': 'Buscar por zona...',
    'search.mobile_placeholder': '¿Dónde quieres vivir?',
    
    // Hero Section
    'hero.title': 'Encuentra tu hogar ideal',
    'hero.subtitle': 'Descubre properties completas o habitaciones en las mejores zonas de la ciudad',
    
    // Filter Section
    'filter.property_type': 'Tipo de renta',
    'filter.both': 'Ambas',
    'filter.property': 'Propiedad',
    'filter.room': 'Habitación',
    'filter.price_filters': 'Filtros',
    'filter.sort_by': 'Ordenar por',
    'filter.clear_filters': 'Limpiar filtros',
    
    // Sort Options
    'sort.newest': 'Más recientes',
    'sort.price_asc': 'Precio: menor a mayor',
    'sort.price_desc': 'Precio: mayor a menor',
    
    // Property Results
    'results.properties_available': 'properties disponibles',
    'results.rooms_available': 'habitaciones disponibles',
    'results.showing_all': 'Mostrando todas las opciones',
    'results.complete_properties': 'properties completas',
    'results.individual_rooms': 'Habitaciones individuales',
    'results.no_properties': 'No se encontraron properties',
    'results.no_properties_subtitle': 'Intenta ajustar tus filtros para ver más opciones',
    
    // Property Card
    'property.bedrooms': 'Recámaras',
    'property.bathrooms': 'Baños',
    'property.area': 'Área',
    'property.price': 'Precio',
    'property.type': 'Tipo',
    'property.furnished': 'Amueblado',
    'property.unfurnished': 'Sin amueblar',
    'property.pets_allowed': 'Mascotas permitidas',
    'property.smoking_allowed': 'Fumar permitido',
    'property.parties_allowed': 'Fiestas permitidas',
    'property.not_allowed': 'No permitido',
    'property.private_bathroom': 'Baño privado',
    'property.shared_bathroom': 'Baño compartido',
    'property.available_from': 'Disponible desde',
    'property.not_found': 'Propiedad no encontrada',
    'property.view_more': 'Ver más',
    'property.view_less': 'Ver menos',
    'property.save': 'Guardar',
    'property.saved': 'Guardado',
    'property.view_details': 'Ver detalles',
    
    // Property Details
    'details.description': 'Descripción',
    'details.amenities': 'Amenidades',
    'details.furnishing': 'Amueblado',
    'details.rules': 'Reglas de la propiedad',
    'details.pets': 'Mascotas',
    'details.smoking': 'Fumar',
    'details.parties': 'Fiestas',
    'details.availability': 'Disponibilidad',
    'details.security': 'Seguridad',
    'details.deposit': 'Depósito',
    'details.commission': 'Comisión',
    'details.share': 'Compartir',
    'details.save': 'Guardar',
    'details.saved': 'Guardado',
    
    // Application Flow
    'application.title': 'Solicitud de Renta',
    'application.step1': 'Tipo de Ocupación',
    'application.step2': 'Fecha de Ocupación',
    'application.step3': 'Duración del Contrato',
    'application.step4': 'Ingresos',
    'application.step5': 'KYC',
    'application.occupation_type': '¿Cuál es tu tipo de ocupación?',
    'application.professional': 'Profesionista',
    'application.student': 'Estudiante',
    'application.entrepreneur': 'Emprendedor',
    'application.occupancy_date': '¿Cuándo planeas mudarte?',
    'application.contract_duration': '¿Por cuánto tiempo necesitas la propiedad?',
    'application.income_info': 'Información de ingresos',
    'application.kyc_verification': 'Verificación de identidad',
    
    // Hoster Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.properties': 'properties',
    'sidebar.tenants': 'Inquilinos',
    'sidebar.operation': 'OPERACIÓN',
    'sidebar.offer': 'OFERTA',
    
    // Hoster Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.temporality': 'Temporalidad',
    'dashboard.month': 'Mes',
    'dashboard.week': 'Semana',
    'dashboard.day': 'Día',
    'dashboard.custom': 'Personalizado',
    'dashboard.totalProperties': 'properties Totales',
    'dashboard.totalIncome': 'Ingresos Totales',
    'dashboard.occupancyRate': 'Tasa de Ocupación',
    'dashboard.avgRent': 'Renta Promedio',
    'dashboard.currentTenants': 'Inquilinos Actuales',
    'dashboard.performanceByTime': 'Comportamiento por Temporalidad',
    'dashboard.startEarning': '¡Comienza a generar ingresos!',
    'dashboard.uploadFirst': 'Carga tu primera propiedad y conecta con inquilinos ideales para ti',
    'dashboard.uploadProperty': 'Cargar mi primera propiedad',
    
    // Dashboard Analytics
    'dashboard.analytics': 'Panel de Analytics',
    'dashboard.sixMonths': '6 Meses',
    'dashboard.twelveMonths': '12 Meses',
    'dashboard.active': 'activas',
    'dashboard.occupied': 'ocupadas',
    'dashboard.estimated': 'estimado',
    'dashboard.totalApplications': 'Total Solicitudes',
    'dashboard.pending': 'pendientes',
    'dashboard.approved': 'aprobadas',
    'dashboard.rejected': 'rechazadas',
    'dashboard.approvalRate': 'Tasa de Aprobación',
    'dashboard.averageRent': 'Renta Promedio',
    'dashboard.perProperty': 'por propiedad',
    'dashboard.annualRevenue': 'Ingresos Anuales',
    'dashboard.projected': 'proyectado',
    'dashboard.applicationStatus': 'Estado de Solicitudes',
    'dashboard.noApplications': 'No hay solicitudes aún',
    'dashboard.financialOverview': 'Resumen Financiero',
    'dashboard.monthlyRevenue': 'Ingresos Mensuales',
    'dashboard.currentMonth': 'Mes actual',
    'dashboard.annualProjection': 'Proyección Anual',
    'dashboard.basedOnCurrent': 'Basado en ingresos actuales',
    'dashboard.totalCollected': 'Total Recaudado',
    'dashboard.toDate': 'A la fecha',
    'dashboard.paymentStatus': 'Estado de Pagos',
    'dashboard.overdue': 'Vencidos',
    'dashboard.topProperties': 'properties Destacadas',
    'dashboard.bestPerforming': 'Mejor Rendimiento',
    'dashboard.applications': 'solicitudes',
    'dashboard.apps': 'sol',
    'dashboard.noProperties': 'No hay properties registradas',
    'dashboard.addPropertyPrompt': 'Agrega tu primera propiedad para ver analytics',
    'dashboard.totalProps': 'properties',
    'dashboard.totalApps': 'Solicitudes',
    'dashboard.avgOccupancy': 'Ocupación Prom.',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.applicationFor': 'Solicitud para',
    'dashboard.noRecentActivity': 'No hay actividad reciente',
    'dashboard.activityWillAppear': 'La actividad aparecerá aquí cuando recibas solicitudes',
    
    // Hoster Properties
    'properties.title': 'Gestión de properties',
    'properties.subtitle': 'Administra tus properties de manera eficiente',
    'properties.addProperty': 'Agregar Propiedad',
    'properties.noProperties': 'No hay properties registradas',
    'properties.addFirst': 'Agrega tu primera propiedad para comenzar',
    
    // Hoster Tenants
    'tenants.title': 'Gestión de Inquilinos',
    'tenants.subtitle': 'Administra la información de tus inquilinos',
    'tenants.addTenant': 'Agregar Inquilino',
    'tenants.noTenants': 'No hay inquilinos registrados',
    'tenants.all': 'Todas',
    'tenants.pending': 'Pendientes',
    'tenants.approved': 'Aprobadas',
    'tenants.rejected': 'Rechazadas',
    'tenants.load_error': 'Error al cargar aplicaciones',
    'tenants.application_updated': 'Aplicación Actualizada',
    'tenants.application_updated_desc': 'La aplicación se actualizó exitosamente',
    'tenants.update_error': 'Error al actualizar aplicación',
    'tenants.no_applications': 'No hay aplicaciones',
    'tenants.with_status': 'con estado',
    'tenants.view_all': 'Ver todas',
    'tenants.status.pending': 'Pendiente',
    'tenants.status.approved': 'Aprobada',
    'tenants.status.rejected': 'Rechazada',
    'tenants.type.student': 'Estudiante',
    'tenants.type.professional': 'Profesional',
    'tenants.type.entrepreneur': 'Emprendedor',
    'tenants.contract_duration': 'Duración del contrato',
    'tenants.move_in_date': 'Fecha de ingreso',
    'tenants.applied_on': 'Aplicó el',
    'tenants.view_details': 'Ver detalles',
    'tenants.addFirst': 'Agrega tu primer inquilino para comenzar',
    
    // Property Flow
    'propertyFlow.title': 'Agregar Nueva Propiedad',
    'propertyFlow.propertyType': 'Tipo de Propiedad',
    'propertyFlow.location': 'Ubicación',
    'propertyFlow.propertyDetails': 'Detalles de la Propiedad',
    'propertyFlow.roomsQuantity': 'Cantidad de Habitaciones',
    'propertyFlow.roomCharacteristics': 'Características de las Habitaciones',
    'propertyFlow.furniture': 'Mobiliario',
    'propertyFlow.pricing': 'Precios',
    'propertyFlow.contracts': 'Contratos',
    'propertyFlow.additionalInfo': 'Información Adicional',
    'propertyFlow.next': 'Siguiente',
    'propertyFlow.previous': 'Anterior',
    'propertyFlow.finish': 'Finalizar',
    'propertyFlow.location_description': '¿Dónde se encuentra tu propiedad?',
    'propertyFlow.select_zone': 'Selecciona una zona',
    'propertyFlow.continue': 'Continuar',
    
    // Property Type Step
    'propertyFlow.offer_type': 'Tipo de Oferta',
    'propertyFlow.offer_type_desc': '¿Cómo quieres rentar tu propiedad?',
    'propertyFlow.full_property': 'Propiedad Completa',
    'propertyFlow.full_property_desc': 'Renta toda la propiedad como una unidad',
    'propertyFlow.by_rooms': 'Por Habitaciones',
    'propertyFlow.by_rooms_desc': 'Renta habitaciones individuales',
    'propertyFlow.property_type': 'Tipo de Propiedad',
    'propertyFlow.property_type_desc': '¿Qué tipo de propiedad es?',
    'propertyFlow.house': 'Casa',
    'propertyFlow.house_desc': 'Propiedad independiente con jardín o patio',
    'propertyFlow.apartment': 'Departamento',
    'propertyFlow.apartment_desc': 'Unidad dentro de un edificio o complejo',
    
    // Property Photos Step
    'propertyFlow.property_photos': 'Fotos de la Propiedad',
    'propertyFlow.property_photos_desc': 'Sube fotos generales de la propiedad (espacios comunes, exterior, etc.)',
    'propertyFlow.click_to_upload': 'Haz clic para subir fotos',
    'propertyFlow.uploading': 'Subiendo fotos...',
    'propertyFlow.upload_instructions': 'JPG, PNG o WebP hasta 5MB cada una. Máximo 10 fotos.',
    'propertyFlow.photo_tips': 'Consejos para mejores fotos',
    'propertyFlow.tip_1': 'Incluye fotos de la sala, cocina, y áreas comunes',
    'propertyFlow.tip_2': 'Toma fotos con buena iluminación natural',
    'propertyFlow.tip_3': 'Muestra el exterior y la entrada de la propiedad',
    'propertyFlow.tip_4': 'Evita fotos borrosas o muy oscuras',
    
    // Room Characteristics Step
    'propertyFlow.room_details': 'Detalles de las Habitaciones',
    'propertyFlow.room_details_desc': 'Configura los detalles de cada habitación',
    'propertyFlow.room_name': 'Nombre de la habitación',
    'propertyFlow.characteristics': 'Características',
    'propertyFlow.furnished': 'Amueblada',
    'propertyFlow.semi_furnished': 'Semi-amueblada',
    'propertyFlow.unfurnished': 'Sin amueblar',
    'propertyFlow.monthly_price': 'Precio mensual (MXN)',
    'propertyFlow.deposit': 'Depósito (opcional)',
    'propertyFlow.available_from': 'Disponible desde',
    'propertyFlow.room_photos': 'Fotos de la habitación',
    'propertyFlow.upload_room_photos': 'Subir fotos de la habitación',
    'propertyFlow.room_photo_instructions': 'Máximo 5 fotos por habitación',
    
    // Additional Info Step
    'propertyFlow.additional_info': 'Información Adicional',
    'propertyFlow.additional_info_desc': 'Completa los detalles de tu propiedad',
    'propertyFlow.property_details': 'Detalles de la propiedad',
    'propertyFlow.square_meters': 'Metros cuadrados',
    'propertyFlow.parking_spaces': 'Estacionamientos',
    'propertyFlow.total_bathrooms': 'Baños totales',
    'propertyFlow.bathrooms_note': '(Incluyendo los de las habitaciones)',
    'propertyFlow.max_roommates': 'Número máximo de compañeros de cuarto',
    'propertyFlow.roommates_note': 'Total de personas que pueden vivir en la propiedad',
    'propertyFlow.parking': 'Estacionamientos',
    'propertyFlow.bathrooms': 'Baños',
    'propertyFlow.roommates': 'Compañeros',
    'propertyFlow.house_rules': 'Reglas de la casa',
    'propertyFlow.pets_allowed': 'Se permiten mascotas',
    'propertyFlow.smoking_allowed': 'Se permite fumar',
    'propertyFlow.parties_allowed': 'Se permiten fiestas',
    'propertyFlow.meetings_allowed': 'Se permiten reuniones de trabajo',
    'propertyFlow.meeting_schedule': 'Horario permitido para reuniones',
    'propertyFlow.rules_summary': 'Resumen de reglas',
    'propertyFlow.pets': 'Mascotas',
    'propertyFlow.smoking': 'Fumar',
    'propertyFlow.parties': 'Fiestas',
    'propertyFlow.work_meetings': 'Reuniones de trabajo',
    
    // Contracts Step
    'contracts.flow_title': 'Configuración de Contratos',
    'contracts.flow_description': 'Configura las opciones de contrato para tu propiedad',
    'contracts.contract_type': 'Tipo de Contrato',
    'contracts.use_template': 'Usar Plantilla',
    'contracts.upload_custom': 'Subir Personalizado',
    'contracts.template_benefits': 'Beneficios de la plantilla estándar',
    'contracts.benefit_1': 'Contrato legalmente válido en México',
    'contracts.benefit_2': 'Incluye todas las cláusulas necesarias',
    'contracts.benefit_3': 'Protección para ambas partes',
    'contracts.benefit_4': 'Actualizado con la legislación vigente',
    'contracts.duration_options': 'Opciones de duración de contrato',
    'contracts.1_month': '1 mes',
    'contracts.2_months': '2 meses',
    'contracts.3_months': '3 meses',
    'contracts.4_months': '4 meses',
    'contracts.5_months': '5 meses',
    'contracts.6_months': '6 meses',
    'contracts.7_months': '7 meses',
    'contracts.8_months': '8 meses',
    'contracts.9_months': '9 meses',
    'contracts.10_months': '10 meses',
    'contracts.11_months': '11 meses',
    'contracts.12_months': '12 meses',
    'contracts.selected_durations': 'Duraciones seleccionadas',
    'contracts.custom_requirements': 'Requisitos para contratos personalizados',
    'contracts.requirement_1': 'Debe ser legalmente válido en México',
    'contracts.requirement_2': 'Incluir cláusulas de protección al inquilino',
    'contracts.requirement_3': 'Formatos: PDF, DOC, DOCX (máx. 5MB)',
    'contracts.requirement_4': 'Será revisado por nuestro equipo legal',
    'contracts.upload_contract_file': 'Subir contrato personalizado',
    'contracts.upload_instructions': 'PDF, DOC o DOCX hasta 5MB',
    'contracts.remove': 'Remover',
    'contracts.deposit_config': 'Configuración de Depósito',
    'contracts.require_deposit': 'Requerir depósito',
    'contracts.deposit_description': 'Los inquilinos deberán pagar un depósito de garantía',
    'contracts.deposit_amount': 'Monto del depósito (MXN)',
    'contracts.room_deposits': 'Depósito por habitación (MXN)',
    'contracts.invalid_file_type': 'Tipo de archivo no válido',
    'contracts.file_type_desc': 'Solo se permiten archivos PDF, DOC y DOCX',
    'contracts.file_too_large': 'Archivo muy grande',
    'contracts.file_size_desc': 'El archivo debe ser menor a 5MB',
    'contracts.file_uploaded': 'Contrato subido',
    'contracts.select_duration': 'Selecciona duración',
    'contracts.select_duration_desc': 'Selecciona al menos una opción de duración de contrato',
    'contracts.upload_contract': 'Sube tu contrato',
    'contracts.upload_contract_desc': 'Sube tu contrato personalizado',
    
    // General
    'apply_to_rent': 'Aplicar para rentar',
    'back': 'Regresar',
    'continue': 'Continuar',
    'send_application': 'Enviar solicitud',
    'close': 'Cerrar',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'loading': 'Cargando...',
    'error': 'Error',
    'success': 'Éxito',
    
    // Favorites
    'favorites.title': 'Mis Favoritos',
    'favorites.empty': 'No tienes properties favoritas',
    'favorites.empty_subtitle': 'Explora properties y guarda las que más te gusten',
    'favorites.remove': 'Remover de favoritos',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido a tu hogar',
    'dashboard.subtitle': 'Gestiona tus properties y solicitudes',
    'dashboard.home.title': 'Mi hogar',
    'dashboard.description': 'Aquí puedes ver el estatus de tus aplicaciones y gestionar tus contratos',
    'dashboard.status.en-revision': 'En revisión',
    'dashboard.status.aprobado': 'Aprobado',
    'dashboard.status.rechazado': 'Rechazado',
    'dashboard.status.pending': 'En revisión',
    'dashboard.status.approved': 'Aprobado',
    'dashboard.status.rejected': 'Rechazado',
    'dashboard.status.withdrawn': 'Retirado',
    'dashboard.appliedOn': 'Aplicaste el',
    'dashboard.congratulations': '¡Felicidades! Tu aplicación fue aprobada',
    'dashboard.daysLeft': 'días restantes',
    'dashboard.contractDeadline': 'Tienes 7 días para firmar el contrato y realizar el pago inicial.',
    'dashboard.signContract': 'Firmar contrato',
    'dashboard.contractSigned': 'Contrato firmado',
    'dashboard.makePayment': 'Realizar pago',
    'dashboard.paymentCompleted': 'Pago realizado',
    'dashboard.underReview': 'Tu aplicación está siendo revisada por el propietario. Te notificaremos cuando tengamos una respuesta.',
    'dashboard.applicationRejected': 'Tu aplicación no fue aceptada en esta ocasión. Puedes aplicar a otras properties disponibles.',
    'dashboard.viewMoreProperties': 'Ver más properties',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.personal_info': 'Información Personal',
    'profile.professional_info': 'Información Profesional',
    'profile.completion': 'Completitud del perfil',
    'profile.name': 'Nombre completo',
    'profile.email': 'Correo electrónico',
    'profile.phone': 'Teléfono',
    'profile.occupation': 'Ocupación',
    'profile.company': 'Empresa',
    'profile.position': 'Puesto',
    'profile.university': 'Universidad',
    'profile.career': 'Carrera',
    'profile.business_name': 'Nombre del negocio',
    'profile.business_type': 'Tipo de negocio',
    
    // Mobile Navigation
    'mobile.documents': 'Documentos',
    
    // Modals
    'modal.price_filter': 'Filtro de Precio',
    'modal.sort': 'Ordenar',
    'modal.zone_search': 'Buscar Zona',
    'modal.apply_filters': 'Aplicar filtros',
    'modal.reset_filters': 'Restablecer',
    
    // Currency and Units
    'currency.mxn': 'MXN',
    'units.m2': 'm²',
    'units.month': '/mes',
    
    // Favorites
    'favorites.added_title': 'Agregado a favoritos',
    'favorites.added_description': 'La propiedad se agregó a tus favoritos',
    'favorites.removed_title': 'Eliminado de favoritos',
    'favorites.removed_description': 'La propiedad se eliminó de tus favoritos',
    'favorites.error_title': 'Error al actualizar favoritos',
    'favorites.error_description': 'Hubo un error al actualizar tus favoritos. Inténtalo de nuevo.',
    
    // KYC (Know Your Customer)
    'kyc.title': 'Verificación de identidad',
    'kyc.description': 'Para completar tu solicitud, necesitamos verificar tu identidad',
    'kyc.required_documents': 'Documentos requeridos',
    'kyc.tenant_id_label': 'Identificación oficial del inquilino',
    'kyc.tenant_id_description': 'INE, pasaporte o cédula profesional',
    'kyc.video_selfie_label': 'Video selfie del inquilino',
    'kyc.video_selfie_description': 'Video corto mostrando tu rostro y diciendo tu nombre completo',
    'kyc.guardian_id_label': 'Identificación oficial del tutor',
    'kyc.guardian_id_description': 'INE, pasaporte o cédula profesional del tutor',
    'kyc.application_summary': 'Resumen de tu solicitud',
    'kyc.property': 'Propiedad',
    'kyc.price': 'Precio',
    'kyc.zone': 'Zona',
    'kyc.submit_application': 'Enviar solicitud',
    'kyc.application_sent': 'Solicitud enviada',
    'kyc.application_sent_description': 'Tu solicitud de renta ha sido enviada exitosamente. El propietario la revisará y te contactará pronto.',
    
    // Common
    'common.back': 'Regresar',
    'common.error': 'Error',
    'common.cancel': 'Cancelar',
    'common.sending': 'Enviando',
    'common.view': 'Ver',
    'common.loading': 'Cargando...',
    
    // Map
    'map.search_placeholder': 'Buscar properties en el mapa...',
    'map.properties_found': 'properties encontradas',
    'map.view_on_map': 'Ver en mapa',
    'map.list_view': 'Vista de lista',
    'map.fullscreen': 'Pantalla completa',
    'map.exit_fullscreen': 'Salir de pantalla completa',
    'propertyFlow.address': 'Dirección',
    'propertyFlow.address_placeholder': 'Escribe la dirección...',
    'propertyFlow.confirm_location': 'Confirmar ubicación',
    'map.demo_mode': 'Modo demo - Configura VITE_MAPBOX_ACCESS_TOKEN para usar el mapa real',
    'map.configure_mapbox': 'Configura Mapbox para ver el mapa interactivo',
    'map.no_address': 'Sin dirección especificada',
    'map.get_current_location': 'Obtener ubicación actual',
    'map.click_drag_instructions': 'Haz clic en el mapa o arrastra el marcador para ajustar la ubicación',
    'map.loading': 'Cargando mapa...',
    'map.coordinates': 'Coordenadas',
    'map.click_to_confirm': 'Haz clic aquí para confirmar la ubicación',

    // Contracts
    'contracts.title': 'Gestión de Contratos',
    'contracts.subtitle': 'Administra el ciclo de vida completo de tus contratos de arrendamiento',
    'contracts.new_contract': 'Nuevo Contrato',
    'contracts.total_contracts': 'Total Contratos',
    'contracts.active_contracts': 'activos',
    'contracts.total_income': 'Ingresos Totales',
    'contracts.average_label': 'Promedio',
    'contracts.occupancy_rate': 'Tasa de Ocupación',
    'contracts.occupied_properties': 'properties ocupadas',
    'contracts.alerts': 'Alertas',
    'contracts.expiring': 'expirando',
    'contracts.overdue_payments': 'pagos vencidos',
    'contracts.contract_status': 'Estado de Contratos',
    'contracts.view_all_contracts': 'Ver Todos los Contratos',
    'contracts.view_all_description': 'Explora y gestiona todos tus contratos de arrendamiento',
    'contracts.create_new_contract': 'Crear Nuevo Contrato',
    'contracts.create_new_description': 'Inicia un nuevo contrato de arrendamiento',
    'contracts.reports_analytics': 'Reportes y Analytics',
    'contracts.reports_description': 'Analiza el rendimiento de tus contratos',
    'contracts.attention_required': 'Atención Requerida',
    'contracts.view_contracts': 'Ver Contratos',
    'contracts.lifecycle_management': 'Gestión del Ciclo de Vida',
    'contracts.contract_singular': 'contrato',
    'contracts.contract_plural': 'contratos',
    'contracts.expires_in_30_days': 'en los próximos 30 días',
    'contracts.payment_singular': 'pago',
    'contracts.payment_plural': 'pagos',
    'contracts.overdue_singular': 'vencido',
    'contracts.overdue_plural': 'vencidos',
    'contracts.expires_singular': 'expira',
    'contracts.expires_plural': 'expiran',
    'contracts.modify_existing': 'Modifica los términos del contrato existente',
    'contracts.complete_info_new': 'Completa la información para crear un nuevo contrato',
    'contracts.success': 'Éxito',
    'contracts.analytics_error': 'No se pudieron cargar las estadísticas',
    
    // Contract Status
    'contract_status.active': 'Activos',
    'contract_status.pending_signatures': 'Pendiente Firmas',
    'contract_status.draft': 'Borradores',
    'contract_status.expired': 'Expirados',
    'contract_status.terminated': 'Terminados',
    'contract_status.cancelled': 'Cancelados',
    'contract_status.pending': 'Pendientes',
    'contract_status.approved': 'Aprobados',
    'contract_status.rejected': 'Rechazados',

    // Contract List & Search
    'contracts.search_placeholder': 'Buscar por propiedad, dirección o inquilino...',
    'contracts.sort_by_date': 'Fecha Creación',
    'contracts.sort_by_start_date': 'Fecha Inicio',
    'contracts.sort_by_end_date': 'Fecha Fin',
    'contracts.sort_by_rent': 'Monto Renta',
    'contracts.no_contracts_yet': 'Aún no has creado ningún contrato.',
    'contracts.no_contracts_found': 'No se encontraron contratos con los filtros aplicados.',
    'contracts.no_contracts_title': 'No hay contratos',
    'contracts.create_first_contract': 'Crear Primer Contrato',
    'contracts.filter_all': 'Todos',
    'contracts.sort_by': 'Ordenar por',
    'contracts.filter_status': 'Estado',
    
    // Contract Form
    'contracts.form_title_edit': 'Editar Contrato',
    'contracts.form_title_create': 'Crear Nuevo Contrato',
    'contracts.property_selection': 'Selección de Propiedad',
    'contracts.tenant_selection': 'Selección de Inquilino',
    'contracts.contract_terms': 'Términos del Contrato',
    'contracts.save_contract': 'Guardar Contrato',
    'contracts.cancel': 'Cancelar',
    'contracts.basic_info': 'Información Básica',
    'contracts.financial_terms': 'Términos Financieros',
    'contracts.deposit': 'Depósito',
    'contracts.payment_day': 'Día de Pago (1-31)',
    'contracts.grace_period': 'Período de Gracia (días)',
    'contracts.policies': 'Políticas',
    'contracts.pet_deposit': 'Depósito por Mascotas',
    'contracts.pet_restrictions_placeholder': 'Ej: Solo perros pequeños',
    'contracts.guests_allowed': 'Huéspedes Permitidos',
    'contracts.max_duration_days': 'Duración Máxima (días)',
    'contracts.max_guests_number': 'Número Máximo',
    'contracts.renewal_terms': 'Términos de Renovación',
    'contracts.automatic_renewal': 'Renovación Automática',
    'contracts.notice_period_days': 'Período de Aviso (días)',
    'contracts.validation_error': 'Error de validación',
    'contracts.deposit_negative_error': 'El depósito no puede ser negativo',
    'contracts.payment_day_error': 'El día de pago debe estar entre 1 y 31',
    'contracts.saving': 'Guardando...',
    'contracts.update_contract': 'Actualizar Contrato',
    'contracts.create_contract': 'Crear Contrato',
    
    // Contract Details
    'contracts.contract_details': 'Detalles del Contrato',
    'contracts.property_info': 'Información de la Propiedad',
    'contracts.tenant_info': 'Información del Inquilino',
    'contracts.payment_schedule': 'Cronograma de Pagos',
    'contracts.documents': 'Documentos',
    'contracts.history': 'Historial',
    'contracts.duration': 'Duración',
    'contracts.days': 'días',
    'contracts.address': 'Dirección',
    'contracts.guests': 'Huéspedes',
    'contracts.renewal': 'Renovación',
    'contracts.automatic': 'Automática',
    'contracts.yes': 'Sí',
    'contracts.no': 'No',
    'contracts.pending_signatures': 'Este contrato está esperando firmas para activarse.',
    
    // Contract Lifecycle
    'contracts.lifecycle_title': 'Ciclo de Vida del Contrato',
    'contracts.current_status': 'Estado Actual',
    'contracts.available_actions': 'Acciones Disponibles',
    'contracts.sign_contract': 'Firmar Contrato',
    'contracts.activate_contract': 'Activar Contrato',
    'contracts.terminate_contract': 'Terminar Contrato',
    'contracts.renew_contract': 'Renovar Contrato',
    'contracts.draft_description': 'El contrato está en proceso de creación',
    'contracts.active_description': 'El contrato está activo y vigente',
    'contracts.activate_description': 'Activar el contrato ya que todas las firmas están completas',
    'contracts.renew_description': 'Extender la duración del contrato',
    'contracts.termination_reason': 'Razón de terminación *',
    'contracts.termination_placeholder': 'Explica la razón para terminar el contrato...',
    'contracts.new_deposit': 'Nuevo depósito',
    'contracts.contract_expiring': 'Contrato próximo a vencer',
    'contracts.expires_in_days': 'Este contrato vencerá en',
    'contracts.day_singular': 'día',
    'contracts.day_plural': 'días',
    'contracts.contract_expired': 'Este contrato venció el',
    'contracts.action_required': 'Es necesario tomar acción inmediata.',
    
    // Contract Signing
    'contract.sign_contract': 'Firma de Contrato',
    'contract.contract_info': 'Información del Contrato',
    'contract.property': 'Propiedad',
    'contract.period': 'Período',
    'contract.monthly_rent': 'Renta Mensual',
    'contract.deposit': 'Depósito',
    'contract.signature_progress': 'Progreso de Firmas',
    'contract.of': 'de',
    'contract.signatures_completed': 'firmas completadas',
    'contract.tenant': 'Inquilino',
    'contract.hoster': 'Anfitrión',
    'contract.guarantor': 'Aval',
    'contract.signed': 'Firmado',
    'contract.pending': 'Pendiente',
    'contract.provide_signatures': 'Proporcionar Firmas',
    'contract.tenant_signature': 'Firma del Inquilino',
    'contract.hoster_signature': 'Firma del Anfitrión',
    'contract.guarantor_signature': 'Firma del Aval',
    'contract.sign_as': 'Firmar como',
    'contract.no_signature_permissions': 'Sin Permisos de Firma',
    'contract.no_signature_permissions_description': 'No tiene permisos para firmar este contrato. Solo las partes involucradas pueden firmar.',
    'contract.send_signatures': 'Enviar Firmas',
    'contract.signature_required': 'Por favor, proporcione al menos una firma antes de continuar.',
    'contract.signatures_submitted': 'Firmas Enviadas',
    'contract.signatures_submitted_description': 'Sus firmas han sido registradas exitosamente.',
    'contract.signing_error': 'Error al Firmar',
    'contract.signing_error_description': 'No se pudieron registrar las firmas. Inténtelo de nuevo.',
    
    // Signature Pad
    'signaturePad.notAvailable': 'Firma no disponible',
    'signaturePad.signHere': 'Firme en el área de arriba',
    'signaturePad.clear': 'Limpiar',
    'signaturePad.confirmSignature': 'Confirmar Firma',
    
    // Contract Card
    'contracts.next_payment': 'Próximo Pago:',
    'contracts.up_to_date': 'Al día',
  },
  en: {
    // Navigation
    'nav.inicio': 'Properties',
    'nav.favoritos': 'Favorites',
    'nav.hogar': 'My Home',
    'nav.perfil': 'Profile',
    
    // Profile Menu
    'profile.view_profile': 'View Profile',
    'profile.login': 'Sign in / Register',
    'profile.register_property': 'Register property',
    'profile.dashboard': 'Dashboard',
    'profile.settings': 'Settings',
    'profile.language': 'Language',

    'profile.logout': 'Sign out',
    'header.language': 'Language',
    'header.english': 'English',
    'header.spanish': 'Español',
    'header.logout': 'Sign out',
    'header.profile': 'Profile',
    
    // Languages
    'language.spanish': 'Español',
    'language.english': 'English',
    
    // Auth
    'auth.signin': 'Sign in',
    'auth.signup': 'Sign up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.role': 'I am a',
    'auth.tenant': 'Tenant',
    'auth.hoster': 'Host',
    'auth.demo_tenant': 'Demo Tenant',
    'auth.demo_hoster': 'Demo Host',
    
    // Search
    'search.placeholder': 'Search by area...',
    'search.mobile_placeholder': 'Where do you want to live?',
    
    // Hero Section
    'hero.title': 'Find your ideal home',
    'hero.subtitle': 'Discover complete properties or rooms in the best areas of the city',
    
    // Filter Section
    'filter.property_type': 'Rental type',
    'filter.both': 'Both',
    'filter.property': 'Property',
    'filter.room': 'Room',
    'filter.price_filters': 'Filters',
    'filter.sort_by': 'Sort by',
    'filter.clear_filters': 'Clear filters',
    
    // Sort Options
    'sort.newest': 'Newest',
    'sort.price_asc': 'Price: low to high',
    'sort.price_desc': 'Price: high to low',
    
    // Property Results
    'results.properties_available': 'properties available',
    'results.rooms_available': 'rooms available',
    'results.showing_all': 'Showing all options',
    'results.complete_properties': 'Complete properties',
    'results.individual_rooms': 'Individual rooms',
    'results.no_properties': 'No properties found',
    'results.no_properties_subtitle': 'Try adjusting your filters to see more options',
    
    // Property Card
    'property.bedrooms': 'Bedrooms',
    'property.bathrooms': 'Bathrooms',
    'property.area': 'Area',
    'property.price': 'Price',
    'property.type': 'Type',
    'property.furnished': 'Furnished',
    'property.unfurnished': 'Unfurnished',
    'property.pets_allowed': 'Pets allowed',
    'property.smoking_allowed': 'Smoking allowed',
    'property.parties_allowed': 'Parties allowed',
    'property.not_allowed': 'Not allowed',
    'property.private_bathroom': 'Private bathroom',
    'property.shared_bathroom': 'Shared bathroom',
    'property.available_from': 'Available from',
    'property.not_found': 'Property not found',
    'property.view_more': 'View more',
    'property.view_less': 'View less',
    'property.save': 'Save',
    'property.saved': 'Saved',
    'property.view_details': 'View details',
    
    // Property Details
    'details.description': 'Description',
    'details.amenities': 'Amenities',
    'details.furnishing': 'Furnishing',
    'details.rules': 'Property rules',
    'details.pets': 'Pets',
    'details.smoking': 'Smoking',
    'details.parties': 'Parties',
    'details.availability': 'Availability',
    'details.security': 'Security',
    'details.deposit': 'Deposit',
    'details.commission': 'Commission',
    'details.share': 'Share',
    'details.save': 'Save',
    'details.saved': 'Saved',
    
    // Application Flow
    'application.title': 'Rental Application',
    'application.step1': 'Occupation Type',
    'application.step2': 'Occupancy Date',
    'application.step3': 'Contract Duration',
    'application.step4': 'Income',
    'application.step5': 'KYC',
    'application.occupation_type': 'What is your occupation type?',
    'application.professional': 'Professional',
    'application.student': 'Student',
    'application.entrepreneur': 'Entrepreneur',
    'application.occupancy_date': 'When do you plan to move?',
    'application.contract_duration': 'How long do you need the property?',
    'application.income_info': 'Income information',
    'application.kyc_verification': 'Identity verification',
    
    // Hoster Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.properties': 'Properties',
    'sidebar.tenants': 'Tenants',
    'sidebar.operation': 'OPERATION',
    'sidebar.offer': 'OFFER',
    
    // Hoster Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.temporality': 'Time Period',
    'dashboard.month': 'Month',
    'dashboard.week': 'Week',
    'dashboard.day': 'Day',
    'dashboard.custom': 'Custom',
    'dashboard.totalProperties': 'Total Properties',
    'dashboard.totalIncome': 'Total Income',
    'dashboard.occupancyRate': 'Occupancy Rate',
    'dashboard.avgRent': 'Average Rent',
    'dashboard.currentTenants': 'Current Tenants',
    'dashboard.performanceByTime': 'Performance by Time Period',
    'dashboard.startEarning': 'Start generating income!',
    'dashboard.uploadFirst': 'Upload your first property and connect with ideal tenants',
    'dashboard.uploadProperty': 'Upload my first property',
    
    // Dashboard Analytics
    'dashboard.analytics': 'Analytics Panel',
    'dashboard.sixMonths': '6 Months',
    'dashboard.twelveMonths': '12 Months',
    'dashboard.active': 'active',
    'dashboard.occupied': 'occupied',
    'dashboard.estimated': 'estimated',
    'dashboard.totalApplications': 'Total Applications',
    'dashboard.pending': 'pending',
    'dashboard.approved': 'approved',
    'dashboard.rejected': 'rejected',
    'dashboard.approvalRate': 'Approval Rate',
    'dashboard.averageRent': 'Average Rent',
    'dashboard.perProperty': 'per property',
    'dashboard.annualRevenue': 'Annual Revenue',
    'dashboard.projected': 'projected',
    'dashboard.applicationStatus': 'Application Status',
    'dashboard.noApplications': 'No applications yet',
    'dashboard.financialOverview': 'Financial Overview',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.currentMonth': 'Current Month',
    'dashboard.annualProjection': 'Annual Projection',
    'dashboard.basedOnCurrent': 'Based on current income',
    'dashboard.totalCollected': 'Total Collected',
    'dashboard.toDate': 'To Date',
    'dashboard.paymentStatus': 'Payment Status',
    'dashboard.overdue': 'Overdue',
    'dashboard.topProperties': 'Featured Properties',
    'dashboard.bestPerforming': 'Best Performing',
    'dashboard.applications': 'applications',
    'dashboard.apps': 'sol',
    'dashboard.noProperties': 'No properties registered',
    'dashboard.addPropertyPrompt': 'Add your first property to see analytics',
    'dashboard.totalProps': 'Properties',
    'dashboard.totalApps': 'Applications',
    'dashboard.avgOccupancy': 'Avg. Occupancy',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.applicationFor': 'Application for',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.activityWillAppear': 'Activity will appear here when you receive applications',
    
    // Hoster Properties
    'properties.title': 'Property Management',
    'properties.subtitle': 'Manage your properties efficiently',
    'properties.addProperty': 'Add Property',
    'properties.noProperties': 'No properties registered',
    'properties.addFirst': 'Add your first property to get started',
    
    // Hoster Tenants
    'tenants.title': 'Tenant Management',
    'tenants.subtitle': 'Manage your tenants information',
    'tenants.addTenant': 'Add Tenant',
    'tenants.noTenants': 'No tenants registered',
    'tenants.all': 'All',
    'tenants.pending': 'Pending',
    'tenants.approved': 'Approved',
    'tenants.rejected': 'Rejected',
    'tenants.load_error': 'Failed to load applications',
    'tenants.application_updated': 'Application Updated',
    'tenants.application_updated_desc': 'Application updated successfully',
    'tenants.update_error': 'Failed to update application',
    'tenants.no_applications': 'No applications',
    'tenants.with_status': 'with status',
    'tenants.view_all': 'View all',
    'tenants.status.pending': 'Pending',
    'tenants.status.approved': 'Approved',
    'tenants.status.rejected': 'Rejected',
    'tenants.type.student': 'Student',
    'tenants.type.professional': 'Professional',
    'tenants.type.entrepreneur': 'Entrepreneur',
    'tenants.contract_duration': 'Contract duration',
    'tenants.move_in_date': 'Move-in date',
    'tenants.applied_on': 'Applied on',
    'tenants.view_details': 'View details',
    'tenants.addFirst': 'Add your first tenant to get started',
    
    // Property Flow
    'propertyFlow.title': 'Add New Property',
    'propertyFlow.propertyType': 'Property Type',
    'propertyFlow.location': 'Location',
    'propertyFlow.propertyDetails': 'Property Details',
    'propertyFlow.roomsQuantity': 'Number of Rooms',
    'propertyFlow.roomCharacteristics': 'Room Characteristics',
    'propertyFlow.furniture': 'Furniture',
    'propertyFlow.pricing': 'Pricing',
    'propertyFlow.contracts': 'Contracts',
    'propertyFlow.additionalInfo': 'Additional Information',
    'propertyFlow.next': 'Next',
    'propertyFlow.previous': 'Previous',
    'propertyFlow.finish': 'Finish',
    'propertyFlow.location_description': 'Where is your property located?',
    'propertyFlow.select_zone': 'Select a zone',
    'propertyFlow.continue': 'Continue',
    
    // Property Type Step
    'propertyFlow.offer_type': 'Offer Type',
    'propertyFlow.offer_type_desc': 'How do you want to rent your property?',
    'propertyFlow.full_property': 'Full Property',
    'propertyFlow.full_property_desc': 'Rent the entire property as one unit',
    'propertyFlow.by_rooms': 'By Rooms',
    'propertyFlow.by_rooms_desc': 'Rent individual rooms',
    'propertyFlow.property_type': 'Property Type',
    'propertyFlow.property_type_desc': 'What type of property is it?',
    'propertyFlow.house': 'House',
    'propertyFlow.house_desc': 'Independent property with garden or patio',
    'propertyFlow.apartment': 'Apartment',
    'propertyFlow.apartment_desc': 'Unit within a building or complex',
    
    // Property Photos Step
    'propertyFlow.property_photos': 'Property Photos',
    'propertyFlow.property_photos_desc': 'Upload general property photos (common areas, exterior, etc.)',
    'propertyFlow.click_to_upload': 'Click to upload photos',
    'propertyFlow.uploading': 'Uploading photos...',
    'propertyFlow.upload_instructions': 'JPG, PNG or WebP up to 5MB each. Maximum 10 photos.',
    'propertyFlow.photo_tips': 'Tips for better photos',
    'propertyFlow.tip_1': 'Include photos of living room, kitchen, and common areas',
    'propertyFlow.tip_2': 'Take photos with good natural lighting',
    'propertyFlow.tip_3': 'Show the exterior and entrance of the property',
    'propertyFlow.tip_4': 'Avoid blurry or very dark photos',
    
    // Room Characteristics Step
    'propertyFlow.room_details': 'Room Details',
    'propertyFlow.room_details_desc': 'Configure the details of each room',
    'propertyFlow.room_name': 'Room name',
    'propertyFlow.characteristics': 'Characteristics',
    'propertyFlow.furnished': 'Furnished',
    'propertyFlow.semi_furnished': 'Semi-furnished',
    'propertyFlow.unfurnished': 'Unfurnished',
    'propertyFlow.monthly_price': 'Monthly price (MXN)',
    'propertyFlow.deposit': 'Deposit (optional)',
    'propertyFlow.available_from': 'Available from',
    'propertyFlow.room_photos': 'Room photos',
    'propertyFlow.upload_room_photos': 'Upload room photos',
    'propertyFlow.room_photo_instructions': 'Maximum 5 photos per room',
    
    // Additional Info Step
    'propertyFlow.additional_info': 'Additional Information',
    'propertyFlow.additional_info_desc': 'Complete your property details',
    'propertyFlow.property_details': 'Property details',
    'propertyFlow.square_meters': 'Square meters',
    'propertyFlow.parking_spaces': 'Parking spaces',
    'propertyFlow.total_bathrooms': 'Total bathrooms',
    'propertyFlow.bathrooms_note': '(Including room bathrooms)',
    'propertyFlow.max_roommates': 'Maximum number of roommates',
    'propertyFlow.roommates_note': 'Total people who can live in the property',
    'propertyFlow.parking': 'Parking',
    'propertyFlow.bathrooms': 'Bathrooms',
    'propertyFlow.roommates': 'Roommates',
    'propertyFlow.house_rules': 'House rules',
    'propertyFlow.pets_allowed': 'Pets allowed',
    'propertyFlow.smoking_allowed': 'Smoking allowed',
    'propertyFlow.parties_allowed': 'Parties allowed',
    'propertyFlow.meetings_allowed': 'Work meetings allowed',
    'propertyFlow.meeting_schedule': 'Allowed schedule for meetings',
    'propertyFlow.rules_summary': 'Rules summary',
    'propertyFlow.pets': 'Pets',
    'propertyFlow.smoking': 'Smoking',
    'propertyFlow.parties': 'Parties',
    'propertyFlow.work_meetings': 'Work meetings',
    
    // Contracts Step
    'contracts.flow_title': 'Contract Configuration',
    'contracts.flow_description': 'Configure contract options for your property',
    'contracts.contract_type': 'Contract Type',
    'contracts.use_template': 'Use Template',
    'contracts.upload_custom': 'Upload Custom',
    'contracts.template_benefits': 'Standard template benefits',
    'contracts.benefit_1': 'Legally valid contract in Mexico',
    'contracts.benefit_2': 'Includes all necessary clauses',
    'contracts.benefit_3': 'Protection for both parties',
    'contracts.benefit_4': 'Updated with current legislation',
    'contracts.duration_options': 'Contract duration options',
    'contracts.1_month': '1 month',
    'contracts.2_months': '2 months',
    'contracts.3_months': '3 months',
    'contracts.4_months': '4 months',
    'contracts.5_months': '5 months',
    'contracts.6_months': '6 months',
    'contracts.7_months': '7 months',
    'contracts.8_months': '8 months',
    'contracts.9_months': '9 months',
    'contracts.10_months': '10 months',
    'contracts.11_months': '11 months',
    'contracts.12_months': '12 months',
    'contracts.selected_durations': 'Selected durations',
    'contracts.custom_requirements': 'Custom contract requirements',
    'contracts.requirement_1': 'Must be legally valid in Mexico',
    'contracts.requirement_2': 'Include tenant protection clauses',
    'contracts.requirement_3': 'Formats: PDF, DOC, DOCX (max. 5MB)',
    'contracts.requirement_4': 'Will be reviewed by our legal team',
    'contracts.upload_contract_file': 'Upload custom contract',
    'contracts.upload_instructions': 'PDF, DOC or DOCX up to 5MB',
    'contracts.remove': 'Remove',
    'contracts.deposit_config': 'Deposit Configuration',
    'contracts.require_deposit': 'Require deposit',
    'contracts.deposit_description': 'Tenants will need to pay a security deposit',
    'contracts.deposit_amount': 'Deposit amount (MXN)',
    'contracts.room_deposits': 'Deposit per room (MXN)',
    'contracts.invalid_file_type': 'Invalid file type',
    'contracts.file_type_desc': 'Only PDF, DOC and DOCX files are allowed',
    'contracts.file_too_large': 'File too large',
    'contracts.file_size_desc': 'File must be smaller than 5MB',
    'contracts.file_uploaded': 'Contract uploaded',
    'contracts.select_duration': 'Select duration',
    'contracts.select_duration_desc': 'Select at least one contract duration option',
    'contracts.upload_contract': 'Upload your contract',
    'contracts.upload_contract_desc': 'Upload your custom contract',
    
    // General
    'apply_to_rent': 'Apply to rent',
    'back': 'Back',
    'continue': 'Continue',
    'send_application': 'Send application',
    'close': 'Close',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    
    // Favorites
    'favorites.title': 'My Favorites',
    'favorites.empty': 'You have no favorite properties',
    'favorites.empty_subtitle': 'Explore properties and save the ones you like most',
    'favorites.remove': 'Remove from favorites',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to your home',
    'dashboard.subtitle': 'Manage your properties and applications',
    'dashboard.home.title': 'My Home',
    'dashboard.description': 'Here you can see the status of your applications and manage your contracts',
    'dashboard.status.en-revision': 'Under Review',
    'dashboard.status.aprobado': 'Approved',
    'dashboard.status.rechazado': 'Rejected',
    'dashboard.status.pending': 'Under Review',
    'dashboard.status.approved': 'Approved',
    'dashboard.status.rejected': 'Rejected',
    'dashboard.status.withdrawn': 'Withdrawn',
    'dashboard.appliedOn': 'Applied on',
    'dashboard.congratulations': 'Congratulations! Your application was approved',
    'dashboard.daysLeft': 'days remaining',
    'dashboard.contractDeadline': 'You have 7 days to sign the contract and make the initial payment.',
    'dashboard.signContract': 'Sign contract',
    'dashboard.contractSigned': 'Contract signed',
    'dashboard.makePayment': 'Make payment',
    'dashboard.paymentCompleted': 'Payment completed',
    'dashboard.underReview': 'Your application is being reviewed by the owner. We will notify you when we have a response.',
    'dashboard.applicationRejected': 'Your application was not accepted this time. You can apply to other available properties.',
    'dashboard.viewMoreProperties': 'View more properties',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.personal_info': 'Personal Information',
    'profile.professional_info': 'Professional Information',
    'profile.completion': 'Profile completion',
    'profile.name': 'Full name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.occupation': 'Occupation',
    'profile.company': 'Company',
    'profile.position': 'Position',
    'profile.university': 'University',
    'profile.career': 'Career',
    'profile.business_name': 'Business name',
    'profile.business_type': 'Business type',
    
    // Mobile Navigation
    'mobile.documents': 'Documents',
    
    // Modals
    'modal.price_filter': 'Price Filter',
    'modal.sort': 'Sort',
    'modal.zone_search': 'Search Zone',
    'modal.apply_filters': 'Apply filters',
    'modal.reset_filters': 'Reset',
    
    // Currency and Units
    'currency.mxn': 'MXN',
    'units.m2': 'm²',
    'units.month': '/month',
    
    // Favorites
    'favorites.added_title': 'Added to favorites',
    'favorites.added_description': 'Property has been added to your favorites',
    'favorites.removed_title': 'Removed from favorites',
    'favorites.removed_description': 'Property has been removed from your favorites',
    'favorites.error_title': 'Failed to update favorites',
    'favorites.error_description': 'There was an error updating your favorites. Please try again.',
    
    // KYC (Know Your Customer)
    'kyc.title': 'Identity Verification',
    'kyc.description': 'To complete your application, we need to verify your identity',
    'kyc.required_documents': 'Required Documents',
    'kyc.tenant_id_label': 'Official tenant identification',
    'kyc.tenant_id_description': 'Driver\'s license, passport, or professional ID',
    'kyc.video_selfie_label': 'Tenant video selfie',
    'kyc.video_selfie_description': 'Short video showing your face and saying your full name',
    'kyc.guardian_id_label': 'Official guardian identification',
    'kyc.guardian_id_description': 'Driver\'s license, passport, or professional ID of the guardian',
    'kyc.application_summary': 'Application Summary',
    'kyc.property': 'Property',
    'kyc.price': 'Price',
    'kyc.zone': 'Zone',
    'kyc.submit_application': 'Submit Application',
    'kyc.application_sent': 'Application Sent',
    'kyc.application_sent_description': 'Your rental application has been sent successfully. The property owner will review it and contact you soon.',
    
    // Common
    'common.back': 'Back',
    'common.error': 'Error',
    'common.cancel': 'Cancel',
    'common.sending': 'Sending',
    'common.view': 'View',
    'common.loading': 'Loading...',
    
    // Map
    'map.search_placeholder': 'Search properties on map...',
    'map.properties_found': 'properties found',
    'map.view_on_map': 'View on map',
    'map.list_view': 'List view',
    'map.fullscreen': 'Fullscreen',
    'map.exit_fullscreen': 'Exit fullscreen',
    'propertyFlow.address': 'Address',
    'propertyFlow.address_placeholder': 'Enter the address...',
    'propertyFlow.confirm_location': 'Confirm location',
    'map.demo_mode': 'Demo mode - Configure VITE_MAPBOX_ACCESS_TOKEN to use real map',
    'map.configure_mapbox': 'Configure Mapbox to view interactive map',
    'map.no_address': 'No address specified',
    'map.get_current_location': 'Get current location',
    'map.click_drag_instructions': 'Click on the map or drag the marker to adjust the location',
    'map.loading': 'Loading map...',
    'map.coordinates': 'Coordinates',
    'map.click_to_confirm': 'Click here to confirm location',

    // Contracts
    'contracts.title': 'Contract Management',
    'contracts.subtitle': 'Manage the complete lifecycle of your lease contracts',
    'contracts.new_contract': 'New Contract',
    'contracts.total_contracts': 'Total Contracts',
    'contracts.active_contracts': 'active',
    'contracts.total_income': 'Total Income',
    'contracts.average_label': 'Average',
    'contracts.occupancy_rate': 'Occupancy Rate',
    'contracts.occupied_properties': 'occupied properties',
    'contracts.alerts': 'Alerts',
    'contracts.expiring': 'expiring',
    'contracts.overdue_payments': 'overdue payments',
    'contracts.contract_status': 'Contract Status',
    'contracts.view_all_contracts': 'View All Contracts',
    'contracts.view_all_description': 'Explore and manage all your lease contracts',
    'contracts.create_new_contract': 'Create New Contract',
    'contracts.create_new_description': 'Start a new lease contract',
    'contracts.reports_analytics': 'Reports & Analytics',
    'contracts.reports_description': 'Analyze your contract performance',
    'contracts.attention_required': 'Attention Required',
    'contracts.view_contracts': 'View Contracts',
    'contracts.lifecycle_management': 'Lifecycle Management',
    'contracts.contract_singular': 'contract',
    'contracts.contract_plural': 'contracts',
    'contracts.expires_in_30_days': 'in the next 30 days',
    'contracts.payment_singular': 'payment',
    'contracts.payment_plural': 'payments',
    'contracts.overdue_singular': 'overdue',
    'contracts.overdue_plural': 'overdue',
    'contracts.expires_singular': 'expires',
    'contracts.expires_plural': 'expire',
    'contracts.modify_existing': 'Modify the existing contract terms',
    'contracts.complete_info_new': 'Complete the information to create a new contract',
    'contracts.success': 'Success',
    'contracts.analytics_error': 'Could not load analytics',
    
    // Contract Status
    'contract_status.active': 'Active',
    'contract_status.pending_signatures': 'Pending Signatures',
    'contract_status.draft': 'Drafts',
    'contract_status.expired': 'Expired',
    'contract_status.terminated': 'Terminated',
    'contract_status.cancelled': 'Cancelled',
    'contract_status.pending': 'Pending',
    'contract_status.approved': 'Approved',
    'contract_status.rejected': 'Rejected',

    // Contract List & Search
    'contracts.search_placeholder': 'Search by property, address or tenant...',
    'contracts.sort_by_date': 'Creation Date',
    'contracts.sort_by_start_date': 'Start Date',
    'contracts.sort_by_end_date': 'End Date',
    'contracts.sort_by_rent': 'Rent Amount',
    'contracts.no_contracts_yet': 'You haven\'t created any contracts yet.',
    'contracts.no_contracts_found': 'No contracts found with the applied filters.',
    'contracts.no_contracts_title': 'No contracts',
    'contracts.create_first_contract': 'Create First Contract',
    'contracts.filter_all': 'All',
    'contracts.sort_by': 'Sort by',
    'contracts.filter_status': 'Status',
    
    // Contract Form
    'contracts.form_title_edit': 'Edit Contract',
    'contracts.form_title_create': 'Create New Contract',
    'contracts.property_selection': 'Property Selection',
    'contracts.tenant_selection': 'Tenant Selection',
    'contracts.contract_terms': 'Contract Terms',
    'contracts.save_contract': 'Save Contract',
    'contracts.cancel': 'Cancel',
    'contracts.basic_info': 'Basic Information',
    'contracts.financial_terms': 'Financial Terms',
    'contracts.deposit': 'Deposit',
    'contracts.payment_day': 'Payment Day (1-31)',
    'contracts.grace_period': 'Grace Period (days)',
    'contracts.policies': 'Policies',
    'contracts.pet_deposit': 'Pet Deposit',
    'contracts.pet_restrictions_placeholder': 'E.g: Small dogs only',
    'contracts.guests_allowed': 'Guests Allowed',
    'contracts.max_duration_days': 'Max Duration (days)',
    'contracts.max_guests_number': 'Maximum Number',
    'contracts.renewal_terms': 'Renewal Terms',
    'contracts.automatic_renewal': 'Automatic Renewal',
    'contracts.notice_period_days': 'Notice Period (days)',
    'contracts.validation_error': 'Validation error',
    'contracts.deposit_negative_error': 'Deposit cannot be negative',
    'contracts.payment_day_error': 'Payment day must be between 1 and 31',
    'contracts.saving': 'Saving...',
    'contracts.update_contract': 'Update Contract',
    'contracts.create_contract': 'Create Contract',
    
    // Contract Details
    'contracts.contract_details': 'Contract Details',
    'contracts.property_info': 'Property Information',
    'contracts.tenant_info': 'Tenant Information',
    'contracts.payment_schedule': 'Payment Schedule',
    'contracts.documents': 'Documents',
    'contracts.history': 'History',
    'contracts.duration': 'Duration',
    'contracts.days': 'days',
    'contracts.address': 'Address',
    'contracts.guests': 'Guests',
    'contracts.renewal': 'Renewal',
    'contracts.automatic': 'Automatic',
    'contracts.yes': 'Yes',
    'contracts.no': 'No',
    'contracts.pending_signatures': 'This contract is waiting for signatures to be activated.',
    
    // Contract Lifecycle
    'contracts.lifecycle_title': 'Contract Lifecycle',
    'contracts.current_status': 'Current Status',
    'contracts.available_actions': 'Available Actions',
    'contracts.sign_contract': 'Sign Contract',
    'contracts.activate_contract': 'Activate Contract',
    'contracts.terminate_contract': 'Terminate Contract',
    'contracts.renew_contract': 'Renew Contract',
    'contracts.draft_description': 'The contract is in the process of creation',
    'contracts.active_description': 'The contract is active and in effect',
    'contracts.activate_description': 'Activate the contract as all signatures are complete',
    'contracts.renew_description': 'Extend the duration of the contract',
    'contracts.termination_reason': 'Termination reason *',
    'contracts.termination_placeholder': 'Explain the reason for terminating the contract...',
    'contracts.new_deposit': 'New deposit',
    'contracts.contract_expiring': 'Contract expiring soon',
    'contracts.expires_in_days': 'This contract will expire in',
    'contracts.day_singular': 'day',
    'contracts.day_plural': 'days',
    'contracts.contract_expired': 'This contract expired on',
    'contracts.action_required': 'Immediate action is required.',
    'contracts.unrecognized_action': 'Unrecognized action',
    'contracts.action_failed': 'Could not execute the action',
    'contracts.termination_reason_required': 'Must provide a reason for termination',
    
    // Contract Signing
    'contract.sign_contract': 'Sign Contract',
    'contract.contract_info': 'Contract Information',
    'contract.property': 'Property',
    'contract.period': 'Period',
    'contract.monthly_rent': 'Monthly Rent',
    'contract.deposit': 'Deposit',
    'contract.signature_progress': 'Signature Progress',
    'contract.of': 'of',
    'contract.signatures_completed': 'signatures completed',
    'contract.tenant': 'Tenant',
    'contract.hoster': 'Host',
    'contract.guarantor': 'Guarantor',
    'contract.signed': 'Signed',
    'contract.pending': 'Pending',
    'contract.provide_signatures': 'Provide Signatures',
    'contract.tenant_signature': 'Tenant Signature',
    'contract.hoster_signature': 'Host Signature',
    'contract.guarantor_signature': 'Guarantor Signature',
    'contract.sign_as': 'Sign as',
    'contract.no_signature_permissions': 'No Signature Permissions',
    'contract.no_signature_permissions_description': 'You do not have permission to sign this contract. Only involved parties can sign.',
    'contract.send_signatures': 'Send Signatures',
    'contract.signature_required': 'Please provide at least one signature before continuing.',
    'contract.signatures_submitted': 'Signatures Submitted',
    'contract.signatures_submitted_description': 'Your signatures have been successfully registered.',
    'contract.signing_error': 'Signing Error',
    'contract.signing_error_description': 'Could not register signatures. Please try again.',
    
    // Signature Pad
    'signaturePad.notAvailable': 'Signature not available',
    'signaturePad.signHere': 'Sign in the area above',
    'signaturePad.clear': 'Clear',
    'signaturePad.confirmSignature': 'Confirm Signature',
    
    // Contract Card
    'contracts.next_payment': 'Next Payment:',
    'contracts.up_to_date': 'Up to date',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es')
  
  const t = (key: string): string => {
    const dict = translations[language] as Record<string, string>
    return dict[key] ?? key
  }
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
